const modal=document.getElementById('request-modal');const form=document.getElementById('oj-request-form');const steps=[...document.querySelectorAll('.oj-form-step')];const progress=document.getElementById('oj-progress-bar');const sendLink=document.getElementById('oj-send-request');let current=1;

const heroCards=[...document.querySelectorAll('.oj-path-card')];
if(heroCards[2]){heroCards[2].dataset.preference='';heroCards[2].innerHTML='<span class="oj-path-icon">📝</span><span><strong>Tell us about the job</strong><small>Answer a few quick questions, then add photos if helpful.</small></span><b aria-hidden="true">→</b>';}
const heroTitle=document.querySelector('.oj-card-top h2');if(heroTitle)heroTitle.textContent='Start with a few details.';
const heroKicker=document.querySelector('.oj-card-kicker');if(heroKicker)heroKicker.textContent='Quick questionnaire';
const heroBadge=document.querySelector('.oj-rating');if(heroBadge)heroBadge.textContent='~60 seconds';
const heroNote=document.querySelector('.oj-card-note');if(heroNote)heroNote.textContent='A few details help us show up prepared. Photos are optional, and the final price is confirmed onsite before we lift anything.';

const step4=document.querySelector('.oj-form-step[data-step="4"]');
if(step4){step4.innerHTML='<span class="oj-form-kicker">Step 4 of 5</span><h2>Anything important we should know?</h2><p>These quick details help us arrive prepared. Skip anything that does not apply.</p><div class="oj-special-grid"><label><input type="checkbox" name="specialItem" value="Mattress or box spring"><span>🛏️ Mattress / box spring</span></label><label><input type="checkbox" name="specialItem" value="Refrigerator or freezer"><span>🧊 Refrigerator / freezer</span></label><label><input type="checkbox" name="specialItem" value="Tires or electronics"><span>♻️ Tires / electronics</span></label><label><input type="checkbox" name="specialItem" value="Heavy or dense material"><span>🧱 Heavy / dense material</span></label></div><label class="oj-notes">Describe the items or anything unusual<textarea name="jobDetails" rows="3" placeholder="Examples: sectional couch, 12 bags, basement stairs, narrow hallway, old fridge..."></textarea></label><label class="oj-photo-upload"><input type="file" id="oj-photo-files" accept="image/*" multiple><span class="oj-photo-upload-icon">📸</span><strong>Add photos if you have them</strong><small>Helpful, never required. We will remind you to attach them when the text opens.</small></label><div id="oj-photo-status" class="oj-photo-status" aria-live="polite"></div><div class="oj-form-nav"><button class="oj-back" type="button" data-back>← Back</button><button class="oj-btn oj-btn-dark" type="button" data-next>Continue →</button></div>'}

const finalStep=document.querySelector('.oj-form-step[data-step="5"]');
if(finalStep){const grid=finalStep.querySelector('.oj-field-grid');if(grid){grid.insertAdjacentHTML('beforeend','<label>How should we respond?<select name="preference"><option value="Text me">Text me</option><option value="Call me">Call me</option></select></label>');}}

const photoFiles=document.getElementById('oj-photo-files');const photoStatus=document.getElementById('oj-photo-status');if(photoFiles){photoFiles.addEventListener('change',()=>{const count=photoFiles.files.length;if(photoStatus)photoStatus.textContent=count?`${count} photo${count===1?'':'s'} selected. When your text opens, attach them there before sending.`:'';});}

function showStep(n){current=n;steps.forEach(s=>s.classList.toggle('is-active',Number(s.dataset.step)===n));progress.style.width=`${Math.min(n,5)*20}%`;const el=steps.find(s=>Number(s.dataset.step)===n);const target=el&&el.querySelector('input,button,select,textarea');if(target)setTimeout(()=>target.focus(),50)}
function openRequest(button){const p=button.dataset.preference;const z=button.dataset.size;if(p){const e=form.querySelector(`select[name="preference"] option[value="${p}"]`);if(e)e.selected=true}if(z){const e=form.querySelector(`input[name="size"][value="${z}"]`);if(e)e.checked=true}showStep(1);modal.showModal()}
function closeRequest(){modal.close()}
document.querySelectorAll('[data-open-request]').forEach(b=>b.addEventListener('click',()=>openRequest(b)));document.querySelectorAll('[data-close-request]').forEach(b=>b.addEventListener('click',closeRequest));modal.addEventListener('click',e=>{if(e.target===modal)closeRequest()});
document.addEventListener('click',e=>{const next=e.target.closest('[data-next]');if(next){const fields={1:'jobType',2:'access',3:'size'};if(fields[current]&&!form.querySelector(`input[name="${fields[current]}"]:checked`)){alert('Please choose an option to continue.');return}showStep(current+1)}const back=e.target.closest('[data-back]');if(back)showStep(current-1)});
form.addEventListener('submit',e=>{e.preventDefault();const needed=[...form.querySelectorAll('[required]')];const blank=needed.find(x=>!x.value.trim());if(blank){blank.focus();alert('Please add your name, mobile number, and ZIP code.');return}const d=new FormData(form);const yn=k=>d.get(k)?'Yes':'No';const special=d.getAll('specialItem');const photoCount=photoFiles?photoFiles.files.length:0;const lines=["Hi Operation Junk - I'd like to request junk removal.",'',`Name: ${d.get('name')}`,`Mobile: ${d.get('phone')}`,`ZIP: ${d.get('zip')}`,`What needs removal: ${d.get('jobType')}`,`Location/access: ${d.get('access')}`,`Stairs: ${yn('stairs')} | Elevator: ${yn('elevator')} | Long carry: ${yn('longCarry')}`,`Estimated pile: ${d.get('size')}`,`Special items: ${special.length?special.join(', '):'None noted'}`,d.get('jobDetails')?`Details: ${d.get('jobDetails')}`:'',`Preferred follow-up: ${d.get('preference')}`,`Preferred callback time: ${d.get('callbackTime')}`,photoCount?`Photos selected: ${photoCount} — I will attach them to this text.`:'',d.get('notes')?`Extra notes: ${d.get('notes')}`:'','', 'Please confirm the next step.'].filter(Boolean);sendLink.href=`sms:+18722225502?&body=${encodeURIComponent(lines.join('\n'))}`;showStep(6)});